### ISSUE TITLE
Incorrect link to "Setting up a development environment"

### ISSUE THREAD

**Issue by mverzilli** [OpenZeppelin/docs.openzeppelin.com#168]
Repro: 

1. Head to https://docs.openzeppelin.com/cli/2.8/getting-started
2. Click on "Setting Up a Development Environment" in the first TIP Box.

Expected: it navigates to `https://docs.openzeppelin.com/learn/setting-up-a-node-project` (I guess?)

Actual: it navigates to `https://docs.openzeppelin.com/cli/2.8/getting-started#learn::set-up-dev-environment`, which results in reloading the same page.

**Comment by frangio** [comment]
Thanks for reporting!

Fixed in https://github.com/OpenZeppelin/openzeppelin-sdk/commit/924aeeee538377364e0b77c53b62323aa8107d2d, and ported to the latest version in the site in https://github.com/OpenZeppelin/openzeppelin-sdk/commit/4e61ae2080fdad11ebc7d3b58f99526cfc1d9a8d.

**Comment by mverzilli** [comment]
I think the issue is more pervasive, probably I just stumbled upon an instance of this: https://github.com/OpenZeppelin/docs.openzeppelin.com/issues/142

Here's another example: https://docs.openzeppelin.com/cli/2.8/publishing-ethereum-package#learn::public-staging.adoc

**Comment by frangio** [comment]
It may be pervasive because of the recent documentation refactoring we did, where it seems we missed updating several links. Because of https://github.com/OpenZeppelin/docs.openzeppelin.com/issues/142 we haven't detected them automatically but I just thought of a way to find them all so I'll try that as soon as I can. In the meantine, if you want, feel free to submit patches to the docs!

**Comment by frangio** [comment]
I'm in the process of fixing most of these. 

https://github.com/OpenZeppelin/openzeppelin-sdk/pull/1517
https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2153
