### ISSUE TITLE
oz deploy got  deployment failed with error: insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by Mehranh** [OpenZeppelin/docs.openzeppelin.com#244]
Hi 

When I run oz deploy on mainnet I get this error:

CrToken got deployment failed with error: insufficient funds for gas * price + value

I have 0.8329846 Ether in my account

truffle-config.js
```

var HDWalletProvider = require("truffle-hdwallet-provider");
require('dotenv').config()  // Store environment-specific variable from '.env' to process.env


module.exports = {

networks: {

mainnet: {
      provider: () => new HDWalletProvider("XXXXXXXX", "https://mainnet.infura.io/v3/XXXXX" ),
      network_id: 1,       // mainnet
      gas: 2200000,
      gasPrice: 150000000000
    }

}
,
 compilers: {
     solc: {
       version: "0.6.12"
     }
  }
};
```

**Comment by abcoathup** [comment]
Hi @Mehranh!  

I’m sorry that you had this issue.  

I recommend testing the deployment first on a public testnet to check the gas limit required to deploy the contract and to do some manual tests interacting with the contract.  (https://docs.openzeppelin.com/learn/connecting-to-public-test-networks) 

You can also check https://www.ethgasstation.info/ for an appropriate gas price.  You can then use the amount of gas to deploy the contract and the gas price to check that you have appropriate funds.
Due to network congestion gas prices are very high currently.

If you are deploying an upgradeable contract then there are three transactions, deploy the implementation contract, deploy the ProxyAdmin contract and then deploy the proxy contract.  If you are deploying a regular contract then this is only one transaction deploying the contract.

If you have questions you can ask in the community forum: https://forum.openzeppelin.com/

**Comment by Mehranh** [comment]
Hi

I am deploying upgradeable,Do you can check my contract on Etherscan?

This is my contract address on testnet 👍 0x49ab1ef9954546cb83d907a1a6481673e360838f
If you can tell me how much I need

Thanks

**Comment by abcoathup** [comment]
Hi @Mehranh,

We discussed and resolved this in the forum, and you were able to deploy your token: https://forum.openzeppelin.com/t/error-initializing-upgradeable-contract-insufficient-funds-for-gas-price-value/3840
I am hence closing this issue.
