### ISSUE TITLE
Missing installation step at the very beginning of the guide produces an error

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [OpenZeppelin/docs.openzeppelin.com#246]
Following the last steps captured in this image, produces the following error:

![image](https://user-images.githubusercontent.com/9479367/94898825-7b948780-0492-11eb-8c78-e9e55602fab9.png)

![image](https://user-images.githubusercontent.com/9479367/94898933-ac74bc80-0492-11eb-87f3-e12d14679a5b.png)

Before trying this I upgraded node version to the one you put in the installation guide:
![image](https://user-images.githubusercontent.com/9479367/94900713-bb10a300-0495-11eb-9bf1-3e2bb80da7ee.png)

**Comment by Luis-Fernando-Molina** [comment]
What was missing was this: 

`npm install --global @openzeppelin/cli`

Found at one of your repos README

**Comment by Luis-Fernando-Molina** [comment]
The last line of the guide in the previous image fails with this error:

![image](https://user-images.githubusercontent.com/9479367/94900488-5ce3c000-0495-11eb-945b-a15416cde8fe.png)

**Comment by abcoathup** [comment]
Hi @Luis-Fernando-Molina!  

I’m sorry that you had this issue. The guides are meant to show installing locally rather than globally.  Apologies if this isn't clear enough.

As for your second error, it looks like you have already run `npx openzeppelin init` so there is already an `.openzeppelin\project.json` file, so you don't need to run this again.  

I notice that you are using Windows.  I recommend using Windows Subsystem for Linux (WSL) as most tools are built and tested for Linux.  See: https://forum.openzeppelin.com/t/solidity-smart-contract-development-on-windows/2110

If you have any questions on using OpenZeppelin you can ask in the community forum: https://forum.openzeppelin.com/

**Comment by Luis-Fernando-Molina** [comment]
Hi, thanks for the clarification.

Indeed I ended up using WSL afterwards. 

One feedback for you: It might be good to clarify that each guide is independent from the others and are not meant to be done sequentially. Somehow I assumed they were all steps of one overall goal and that was the root of my confusion.

Cheers!

**Comment by frangio** [comment]
The guides are no longer using OpenZeppelin CLI.
